# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('when', models.DateTimeField(default=datetime.datetime(2016, 11, 4, 9, 15, 57, 87659, tzinfo=utc))),
                ('where', models.CharField(default='Moscow', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('img', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('bdate', models.DateTimeField(verbose_name='birthdate')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Participant')),
            ],
        ),
    ]
